import { Injectable } from '@angular/core';
import { Tag } from '../model/tag';


@Injectable({
  providedIn: 'root'
})
export class TagsService {

  private tags = new Array<Tag>();
  private autoGeneratedId = 0;


  constructor() { }

  salvarTag() {
    localStorage.setItem('tags', JSON.stringify(this.tags));
    localStorage.setItem('tagsAutoGeneratedId', this.autoGeneratedId.toString());
  }

  atualizarTag() {
    this.tags = JSON.parse(localStorage.getItem('tags'));
    if (this.tags == null) {
      this.tags = new Array<Tag>();
    }
    const autoId = localStorage.getItem('tagsAutoGeneratedId');
    if (autoId) {
      this.autoGeneratedId = Number(autoId);
    }
  }

  inserirTag(tags: Tag) {
    tags.id = this.autoGeneratedId;
    this.tags.push(tags);
    this.autoGeneratedId++;

    this.salvarTag();
  }

  listarTag(): Array<Tag> {
    this.atualizarTag();
    return this.tags;
  }

  remover(id: number) {
    for (let i = 0; i < this.tags.length; i++) {
      const tag = this.tags[i];

      if (id === tag.id) {
        this.tags.splice(i, 1);
        break;
      }
    }
    this.salvarTag();
  }

  editarTag(tag: Tag) {
    for (let i = 0; i < this.tags.length; i++) {
      const t = this.tags[i];
      if (t.id === tag.id) {
        this.tags[i] = tag;
        break;
      }
    }
    this.salvarTag();
  }
}
